### ISSUE TITLE
Update documentation for Laravel 5.5+ and composer installation

### ISSUE THREAD

**Issue by nathan-io** [jessedp/php-timezones#2]
Thanks again for this useful package. Wanted to suggest a couple of updates to the readme.

> Finally, after the update completes, add the service provider.

This step is no longer necessary since Laravel 5.5 introduced automatic package discovery.

> First, edit your project's composer.json file to require jessedp/php-timezones ... Next, update Composer 

It would be faster (and safe) to let Composer handle this via: `composer require jessedp/php-timezones`. 

That method would also limit the operation merely to installing your package and its dependency - versus a full `composer update`, which could potentially introduce a breaking change from some unrelated vendor package.

It also better aligns with a lot of production deployment scripts which would typically include something like `composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader` rather than `composer update`.

**Comment by jessedp** [comment]
Assuming I get to #1 , I'll take care of this as well. 

If you've never tried, this is something you could try to update directly (it'll still ask me to confirm). Just hit the edit/pencil icon in the top right corner of the readmen/home page docs and "submit a pull request".
